networks:
    appnet:

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/php.dockerfile
            target: development
            args:
                USER_ID: ${UID:-1000}
                GROUP_ID: ${GID:-1000}
        ports:
            - ${APP_PORT:-80}:8080
        volumes:
            - ./src:/var/www/html
        networks:
            - appnet

    phpcli:
        build:
            context: .
            dockerfile: ./docker/phpcli/phpcli.dockerfile
            target: development
            args:
                USER_ID: ${UID:-1000}
                GROUP_ID: ${GID:-1000}
        volumes:
            - ./src:/var/www/html
        networks:
            - appnet

    postgres:
        build:
            context: .
            dockerfile: ./docker/pg/pg.dockerfile
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        volumes:
            - ./docker/data/postgres:/var/lib/postgresql/data
            - ./docker/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        networks:
            - appnet

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - appnet
