networks:
    appnet:

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/php.dockerfile
            target: development
            args:
                USER_ID: ${UID:-1000}
                GROUP_ID: ${GID:-1000}
        ports:
            - ${APP_PORT:-80}:8080
        volumes:
            - ./src:/var/www/html
        networks:
            - appnet

    mysql:
        image: mariadb:lts
        restart: unless-stopped
        tty: true
        ports:
            - ${DB_PORT:-3306}:3306
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - appnet
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
            MARIADB_DATABASE: ${DB_DATABASE:-laravel}

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - appnet

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin
        restart: always
        ports:
            - ${DB_ADMIN_UI:-8080}:80
        networks:
            - appnet
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME:-root}
            MYSQL_USER: ${DB_USERNAME:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-}
            PMA_HOST: mysql

    node:
        image: node:alpine3.19
        working_dir: "/usr/app"
        volumes:
            - ./src:/usr/app
        networks:
            - appnet

    vite:
        image: node:alpine3.19
        working_dir: "/usr/app"
        entrypoint: ["npm", "run", "dev"]
        volumes:
            - ./src:/usr/app
        ports:
            - "${NODE_PORT:-5173}:5173"
        networks:
            - appnet

    mailpit:
        container_name: "mailpit"
        image: axllent/mailpit:v1.16
        restart: unless-stopped
        ports:
            - ${MAILPIT_WEBUI:-8025}:8025
            - ${MAILPIT_SMTP:-1025}:1025
        volumes:
            - ./docker/data/mailpit:/data
        networks:
            - appnet
        environment:
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ALLOW_INSECURE: true
            MP_MAX_MESSAGES: ${MAILPIT_MESSAGES:-100}
