name: gitlabmx

version: "3.9"

networks:
    labmx:
        name: labmx

services:
    nginx:
        container_name: "gl-nginx"
        depends_on:
            - php
            - mysql
            - redis
        build:
            context: ./docker/nginx
            dockerfile: nginx.dockerfile
        ports:
            - 9000:80
            - 9443:443
        volumes:
            - .:/var/www/html
        networks:
            - labmx

    php:
        container_name: "gl-php"
        build:
            context: ./docker/php
            dockerfile: php.dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - labmx

    mysql:
        container_name: "gl-db"
        image: mariadb:lts
        ports:
            - 4406:3306
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - labmx
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
            MARIADB_DATABASE: ${DB_DATABASE}

    composer:
        container_name: "gl-composer"
        image: composer:latest
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - labmx

    node:
        image: node:alpine3.19
        depends_on:
            - nginx
            - php
        container_name: "gl-node"
        working_dir: "/usr/app"
        volumes:
            - .:/usr/app
        command: "npm run dev"
        ports:
            - "5173:5173"
        networks:
            - labmx

    phpmyadmin:
        container_name: "gl-dbadmin"
        depends_on:
            - mysql
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        networks:
            - labmx
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            PMA_HOST: mysql

    artisan:
        container_name: "gl-artisan"
        build:
            context: ./docker/php
            dockerfile: php.dockerfile
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        volumes:
            - .:/var/www/html
        networks:
            - labmx

    redis:
        container_name: "gl-redis"
        image: redis:latest
        ports:
            - 9379:6379
        networks:
            - labmx
