version: "3.9"

networks:
    appnet:
        name: appnet

services:
    nginx:
        container_name: "nginx"
        depends_on:
            - php
            - mysql
            - redis
        build:
            context: ./docker/nginx
            dockerfile: nginx.dockerfile
        ports:
            - ${APP_PORT:-9000}:80
        volumes:
            - .:/var/www/html
        networks:
            - appnet

    php:
        container_name: "php"
        build:
            context: ./docker/php
            dockerfile: php.dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - appnet

    mysql:
        container_name: "db"
        image: mariadb:lts
        ports:
            - ${DB_PORT:-3306}:3306
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - appnet
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
            MARIADB_DATABASE: ${DB_DATABASE}

    composer:
        container_name: "composer"
        image: composer:latest
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - appnet

    node:
        image: node:alpine3.19
        depends_on:
            - nginx
            - php
        container_name: "node"
        working_dir: "/usr/app"
        volumes:
            - .:/usr/app
        command: "npm run dev"
        ports:
            - "${NODE_PORT:-5173}:5173"
        networks:
            - appnet

    phpmyadmin:
        container_name: "dbadmin"
        depends_on:
            - mysql
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        networks:
            - appnet
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            PMA_HOST: mysql

    artisan:
        container_name: "artisan"
        build:
            context: ./docker/php
            dockerfile: php.dockerfile
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        volumes:
            - .:/var/www/html
        networks:
            - appnet

    redis:
        container_name: "redis"
        image: redis:latest
        ports:
            - 9379:6379
        networks:
            - appnet
